server:
  port: 8080

spring:
  application:
    name: rag-chaos-java
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      
langchain4j:
  tavily:
    api-key: ${TAVILY_SECRET}  # key ikkada
    
chatModel:
  baseURL: ${AI_URL}
  model: ${MODEL}
  temperature: 0.7
  apiKey: ${API_KEY_MODEL}
  timeout: 120

logging:
  level:
    root: INFO
    dev.langchain4j: TRACE
    ai.staff.rag: DEBUG